version: '3'

services:
  icecast:
    image: "infiniteproject/icecast"
    ports:
      - "${ICECAST_PORT:-8000}:8000"
    environment:
      - ICECAST_SOURCE_PASSWORD
      - ICECAST_ADMIN_PASSWORD
      - ICECAST_RELAY_PASSWORD
      - ICECAST_HOSTNAME

  liquidsoap:
    image: "phasecorex/liquidsoap"
    command: ["/script.liq"]
    environment:
      - ICECAST_SOURCE_PASSWORD
      - STREAM_NAME
      - STREAM_DESC
      - STREAM_URL
      - STREAM_MOUNTPOINT
    depends_on:
      - icecast
    volumes:
      - ./music:/music:ro
      - ./script.liq:/script.liq:ro
